name: Android Build Test

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "corretto"

      - name: Set Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grand Gradlew Permission
        id: grand_gradlew_permission
        run: chmod +x gradlew

      - name: Validate Gradlew
        id: validate_gradlew
        uses: gradle/wrapper-validation-action@v1

      - name: Set Up Gradle
        id: setup_gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        id: build_with_gradle
        run: ./gradlew build

      - name: Lint
        id: lint
        run: ./gradlew ktlintCheck

      - name: Instrumented Test
        id: instrumented_test
        run: ./gradlew connectedExampleInstrumentedTestAndroidTest

      - name: Unit Test
        id: unit_test
        run: ./gradlew testExampleUnitTestUnitTest

      - name: Build debug APK
        id: build_debug_apk
        run: bash ./gradlew assembleDebug --stacktrace

      # AppTester 배포 루틴 추가 필요
      # app/build/outputs/apk/dev/debug/app-dev-debug.apk


      # REPORT

      # CHECK ERROR
      - name: Check If Grand Gradlew Permission Failed
        if: ${{ failure() && steps.grand_gradlew_permission.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=Grand Gradlew Permission" >> $GITHUB_ENV

      - name: Check If Validate Gradlew Failed
        if: ${{ failure() && steps.validate_gradlew.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=Validate Gradlew Permission" >> $GITHUB_ENV

      - name: Check If Set Up Gradle Failed
        if: ${{ failure() && steps.setup_gradle.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=Set Up Gradle" >> $GITHUB_ENV

      - name: Check If Build with Gradle Failed
        if: ${{ failure() && steps.build_with_gradle.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=Build with Gradle" >> $GITHUB_ENV

      - name: Check If Lint Failed
        if: ${{ failure() && steps.lint.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=Lint" >> $GITHUB_ENV 

      - name: Check If Instrumented Test Failed
        if: ${{ failure() && steps.instrumented_test.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=Instrumented Test" >> $GITHUB_ENV 

      - name: Check If Unit Test Failed
        if: ${{ failure() && steps.unit_test.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=Unit Test" >> $GITHUB_ENV 

      - name: Check If Build debug APK Failed
        if: ${{ failure() && steps.build_debug_apk.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=Build debug APK" >> $GITHUB_ENV

      - name: Set Notification Line Color Red
        if: ${{ failure() }}
        run: |
          echo "LINE_COLOR=ff0800" >> $GITHUB_ENV

      - name: Set Notification Line Color Green
        if: ${{ job.status }} != 'failure'
        run: |
          echo "LINE_COLOR=28a745" >> $GITHUB_ENV

      - name: Send Slack notification
        id: slack
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C04CXA6KPQW"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Result for ${{ github.job }} : ${{ github.event_name }}",
              "attachments": [
                {
                  "color": "${{ env.LINE_COLOR }}",
                  "fields": [
                    {
                      "title": "Status: ${{ job.status }}",
                      "short": true,
                      "value": "${{ github.job }} in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }} on step ${{ env.FAILED_STEP }}."
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_APP }}
