name: Android Build Test

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Check PR title
        if: ${{ github.event.issue.pull_request }}
        env:
          TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ "$TITLE" =~ ^swit- ]]; then
          echo "PR title valid"
          else
            echo "PR title invalid"
            exit 1
            fi

      - name: Get PR Issue Number
        if: ${{ github.event.issue.pull_request }}
        run: |
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "corretto"

      - name: Set Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grand Gradlew Permission
        id: grand_gradlew_permission
        run: chmod +x gradlew

      - name: Validate Gradlew
        id: validate_gradlew
        uses: gradle/wrapper-validation-action@v1

      - name: Set Up Gradle
        id: setup_gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        id: build_with_gradle
        run: ./gradlew build

#      - name: Lint
#        id: lint
#        run: ./gradlew ktlintCheck

      # 연결된 기기가 있을 경우
#      - name: Instrumented Test
#        id: instrumented_test
#        run: ./gradlew connectedAndroidTest

#      - name: Unit Test
#        id: unit_test
#        run: ./gradlew test

#      - name: Clean Gradle
#        run: ./gradlew clean

      # 테스트니까 메인 브랜치로
      # 실제로는 아마 main 에 머지할 때는 release , staging 은 stage , dev 는 debug
      - name: Build debug APK
        id: build_debug_apk
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./gradlew assembleDebug --stacktrace

      # AppTester 배포 루틴 추가 필요
      # unofficial plugin 쓰기 싫은데. 방법 없을까?
      # app/build/outputs/apk/debug/app-debug.apk

      # REPORT

      # CHECK ERROR
      - name: Check If Grand Gradlew Permission Failed
        if: ${{ failure() && steps.grand_gradlew_permission.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=on step Grand Gradlew Permission" >> $GITHUB_ENV

      - name: Check If Validate Gradlew Failed
        if: ${{ failure() && steps.validate_gradlew.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=on step Validate Gradlew Permission" >> $GITHUB_ENV

      - name: Check If Set Up Gradle Failed
        if: ${{ failure() && steps.setup_gradle.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=on step Set Up Gradle" >> $GITHUB_ENV

      - name: Check If Build with Gradle Failed
        if: ${{ failure() && steps.build_with_gradle.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=on step Build with Gradle" >> $GITHUB_ENV

      - name: Check If Lint Failed
        if: ${{ failure() && steps.lint.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=on step Lint" >> $GITHUB_ENV 

      - name: Check If Instrumented Test Failed
        if: ${{ failure() && steps.instrumented_test.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=on step Instrumented Test" >> $GITHUB_ENV 

      - name: Check If Unit Test Failed
        if: ${{ failure() && steps.unit_test.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=on step Unit Test" >> $GITHUB_ENV 

      - name: Check If Build debug APK Failed
        if: ${{ failure() && steps.build_debug_apk.conclusion == 'failure' }}
        run: |
          echo "FAILED_STEP=on step Build debug APK" >> $GITHUB_ENV

      - name: Set Notification Line Color Red
        if: ${{ failure() }}
        run: |
          echo "LINE_COLOR=ff0800" >> $GITHUB_ENV

      - name: Set Notification Line Color Green
        if: ${{ job.status }} != 'failure'
        run: |
          echo "LINE_COLOR=28a745" >> $GITHUB_ENV

      - name: Send Slack notification
        id: slack
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C04CXA6KPQW"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Result for ${{ github.job }} : ${{ github.event_name }}",
              "attachments": [
                {
                  "color": "${{ env.LINE_COLOR }}",
                  "fields": [
                    {
                      "title": "Status: ${{ job.status }}",
                      "short": true,
                      "value": "${{ github.job }} in workflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }} ${{ env.FAILED_STEP }}."
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_APP }}
