name: Android Build Test

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: "corretto"

      - name: Set Android SDK
        uses: android-actions/setup-android@v2

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grand gradlew permission
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew --no-daemon build

#      - name: Gradle Build
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: --stacktrace -Dtrace :app:testDevDebugUnitTest :app:assembleDevDebug :app:assemblePreprodRelease
#        env:
#          TERM: dumb

      - name: Lint
        run: ./gradlew ktlintCheck

      - name: Unit Test
        run: ./gradlew test --tests ExampleUnitTest

      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace

      # AppTester 배포 루틴 추가 필요
      # app/build/outputs/apk/dev/debug/app-dev-debug.apk

      - name: Send Slack notification
        id: slack
        if: always()
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: "C04CXA6KPQW"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "${{ github.job }} Status: ${{ job.status }}",
              "attachments": [
                {
                  "pretext": "Test ${{ job.status }}",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "${{ github.job }} in workflow ${{ gㅑthub.workflow }} of ${{ github.repository }} ahs ${{ job.status }}."
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_APP }}
